version: "3.7"

services:
  web:
    image: bitcoinscala/oracle-server-ui-proxy:latest
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - ORACLE_SERVER_API_URL=http://10.21.21.61:9998/
    ports:
      - 3010:3001
    networks:
      default:
        ipv4_address: 10.21.21.60
    depends_on: 
      - oracleserver
  oracleserver:
    image: 1.7.0-172-48213d9b-20210922-1007-SNAPSHOT
    user: "1000:1000"
    volumes:
      - ${APP_DATA_DIR}/data/oracleserver:/home/bitcoin-s/.bitcoin-s
    environment:
      - BITCOIN_S_KEYMANAGER_ENTROPY=$APP_SEED  
    expose:
      - 9998
    networks:
      default:
        ipv4_address: 10.21.21.61